- Exprimer les coordonnées d’un vecteur dans une base orthonormée.
- Utiliser le système de coordonnées cartésiennes.
- Utiliser le système de coordonnées cylindriques.
- Utiliser le système de coordonnées sphériques.